version: '3.9'
services:

  postgres:
    image: postgres:13.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 10

  employee:
    image: kovalev-employee-task:0.0.1-SNAPSHOT
    depends_on:
      postgres:
        condition: service_healthy
    stdin_open: true
    tty: true
    environment:
      - EMPLOYEE_DB_URL=jdbc:postgresql://postgres:5432/employee